CREATE TABLE IF NOT EXISTS services (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  serviceName TEXT NOT NULL,
  status TEXT NOT NULL,
  currentStatus TEXT NOT NULL,
  lastUpdated TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AdminEmails (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    added_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
